### ISSUE TITLE
SSL certificates and instructions

### ISSUE THREAD

**Issue by bilkusg** [mjarosie/SaturnWithIdentityServerClientCredentials#1]
Thanks for this sample - I found it very helpful in trying to work out how best to authenticate a Saturn/Fable app I'm writing. One thing though, it may be worth adding to the instructions the importance of running 
````
dotnet dev-certs https --trust
```` 
before testing the application. Otherwise you get lots of errors about untrusted certificates.

Also, for what it's worth, I've updated my local copy to use .net5 and it seems to work

**Comment by mjarosie** [comment]
Thanks for letting me know, I'm glad it was helpful! : ) I've updated instructions to mention the certificates command. I'll leave it at .net3.1 as I'm not sure what exactly needs updating apart from `.xsproj` files (paket, sln file etc.) and I don't want to break things.
